language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ravisku/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=True ravisku/docker-react npm run test

